timezone: "Asia/Tokyo"
url: "https://emergent-reasons.github.io"
baseurl: ""

# --- Theme settings --- #

theme: jekyll-theme-tactile
title: "Emergent Reasons"
description: "Sandbox"

# --- Other settings --- #

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
  - .idea/
